version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - ./django_project:/app
    env_file:
      - env
    build:
      context: .
    networks:
      - internal
    depends_on:
      - db
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8080:80"
    depends_on:
      - django_gunicorn
    networks:
      - internal
  
  db:
    image: postgres:12
    container_name: django_db
    environment: 
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=<PASSWORD>
    networks:
      - internal

networks:
  internal:
    name: internal

volumes:
  static:

