# Generated by Django 3.2.3 on 2023-09-11 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='almuno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('apellidoP', models.CharField(max_length=50)),
                ('apellidoM', models.CharField(max_length=50)),
                ('fec_nac', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='asingatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='asignaturasXAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.asingatura')),
                ('Aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.almuno')),
            ],
        ),
    ]
